id: P7B55AB8B
initial_creation_type: ocr
source_metadata:
  volumes:
    a15cb1af386f4b5f9592dd2e7c9a54e6:
      base_file: v096.txt
      image_group_id: I1PD95941
      title: སྲིད་པ་ལས་འདས་པའི་གཏམ།
      total_pages: 1144
      volume_number: 96
